if: type not IN (pull_request) and branch not IN(develop)
dist: trusty
sudo: false
language: minimal
env:
  global:
  - IMAGE=fiware/orion-ld
  - secure: DEqJcF/MXhTPbGMKhtH7lolaK4p8cA1lybMGQ1N1Dq/z/B6I8mDaf3Wuu48ufbW2eXvFfjLiMuoT0sXmFdokmf7jxk2K7uTYgTE4EUzfaks78YC144gpu5fqO/5omeiUi/D8St82HCZSk1KREZ8h1qZCRb1rMCAq03ZFgGxWydFregtp5EKdSZM2rVp0mpuQzNm28INkoRP08xXdpA0kVI+Ue8yeTwUHzhbt7/XOIlLkxHU3MDs73uOMFrCiVNSHpzPH4fS7/6LR/A1k0z3E6Y1aBnXlR3hwm5+4XOmuK3DJSFP0dtOKo6/7FZIfnlKI6QkvU6+vVVfP1U7Tw/cnCaXdSXKCDvqRSHR30bIUYeC6ounftm1JjoSALko00anjTdt2ZOYnqmg9Jqi5Xjz8A88V2+nH9Z0s9Ry1SOY7NulBA4uWAORPm/0zBYjZv7n2Ma1fMU4K05uAKaiTse6gg/oVVw/JC/VvQZFNmALgRg8U8FedbJ8+Zs5Lez98aZfLp1gEH60ypy8Vt73Ftbb0BF1ZfnQrhVFow/LIhCNypS4HLg2M0OQ2qGKmtdTrPhg5Ym23iJF1IOcCu9YMS065gaPHEDiKajXyd2NXUaqoi22fo4KL3C2W91uqCLslvdzVPaE2tV9ubQC6+gEIQ5dHrIWFFjGQoNREzSoaTQ2LYIc=
  - secure: PTDeCK7728qOVcvv4e2Dcod8cR/PjefzxseZdxW+I6JMBUL2Sk2VFKe+mun+Ui8OZavBtXQNNCIaoj3j5ivF/U+vsuwvPhTX7tLSq1ZBwxZUIoP5vC92xH/Phukgmgfmw8/0glP0ji2jIHjv/YOO08E82tmtlV1VRLTeaVvtsQjhd59XG6/tJ6FhAWcqz1IZXIpu/WDW1Pjrt8/bunMViqzVcPW5uAId3sH5OPd+4+pHrru5Wm6gikK3iJFdKdF+pCrVhKDcUp1iaaXmjBs+YHI7HNlxHl3BRljulEpUR6vX89gpqDbItDl62e15Ob5ZqSjHlznbFRR9rqVYnouD6PfOL9opU6u6icXrcdLrplimOTGghEeQiQwV65rSCILWVV9s37L/7c3UGc7yhDxisuTXGLNV4/D9fpRr1PgSvxPMrbMQ7GjoHrGlAH2qU8vvH6Jf6SouT6FTaLr1QZI3pKaHzjMUIbXpgkdZZVtXcZfvgXZOS8gKJ03jHIhqrYP8XT2GG/BVNAnK4xxARiUZmCp3TOG9puotG63ThHNWO6aAZiAhm1489E72IyR4OYR43DKj5PLQ3+PqwmmC0vlKT50Z7bhwy4n1FxjvycwC78wOzl3uO2b1OG/N5XP6dDFhlX85B65f1mIadq02QPNPEdwopIcrjc1noXWub2Kx/kA=
  - secure: eLj+VEP4SjSdJMTZMn9DGL1v/K+CeGYnaxgrux7MpNN13ALSQeq0w7b9TTxD3n+wFMEE/aFAst19Zxfz5dIftgfcoj/WMBzWUDiBtPeoaGe+Nf+kQdnPf1SrVRolmiaWGqC853/2qqJtWFsv1YekUYU6xbV0r6Rw/bO9A2qj5lLgMSOC71BpOCBAN26gUgslWSdDX1O2eNjRHGpDcvV8KNFLDoscDdyMDFZv0FTDH1mtKzAGoD6xfk7b8r91aPb4vQvrKywE0e4UC1fag8h6vzqPqVSkaQ+l4uXjiDHZW/rm+TZTZhnREI6b6kG+QjrhmqJaltUFIjnN1WmoIRQlFEA4QJ9yYzmJHuzZ0+rxGD7pkm2na9u6MXrZ68X4UtvvkYf8rs7TFWQCQNnyW8KZZz7gd6mNEOmB2dOVW2V6jujq+v++e6GpHCncF+WIY4iAyjsxBEDzzGavUKCPMEk5RG73hPrW/f8Z6iKSFjYSk8rary70pEKdDZ/syZcI4dLw1vNWA6/FAHjzT3SN/dxb6f80b0TiRhV6IZAIk2JHcHsCWc5W6TXVk1Iqjju3IlhcsUMigToarZGzRM+OrOEW/uKEh+/If++G6QDKUqfEkKDQLYr4VwYLH3Bo0tGH8P13H9mBQ8Wii5aa4ZOFdjpY6XO3QEvlP/L4R+ov9Z2XWvs=
before_install: true
install: true
before_script: git lfs pull
script:
- echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
- docker build --build-arg TOKEN=${TOKEN} --build-arg REV=${TRAVIS_COMMIT} --build-arg TEST=True -t ${IMAGE} -f docker/Dockerfile docker/
- docker push ${IMAGE}
notifications:
  email:
    recipients:
    - ken.zangelin@fiware.org
    - josemanuel.cantera@fiware.org
    - dmitrii.demin@fiware.org
    on_success: never
    on_failure: always
