if: type not IN (pull_request) and branch not IN(develop)
dist: trusty
sudo: false
language: minimal
env:
  global:
  - IMAGE=fiware/orion-ld
  - secure: nvIJCAsSHhIoEV/0SJ1hlw+XZWUSqHg+DhTLJvHJGHbolxCXNbzzFhu+Dyp+1xqKaGQqQ3/bZQSAgVtip+m2Mg0dirWQZJ7RMqv5gAteRPNvbYjL3nb5+2s2/QsJ5AQpT4YaZolIGvKHP9/nxrDL42sUnZxltXy2hhZkONCXqZuisHtbTWNklgU+P9Uv87+21B9aXo0YofjflCvAvoVPiVGTVekXD2DCVv6umUqXyIhCALEPmr4gbu9dPi36L46eq2zK3XYkcyJShc6HUdj6f+s7VcHCrIN/EV58SvXNi2Me8tHYR+jIgwOTSPgTCG+Y1yNm88udPylrruLG93Po1ZA9W0dZWNXaQQoytT7rXHXVS8uZsZqwulhFMNKdU40Q6QtefggOclPfF+/1eLH6ETYAS7xrHmEGALpzghCjRMPgcNSdTZvLNeom10B5NkNrEWSuBxojgXL43v503zP2SfQvZ5ybBVCIKcbcOtK4A7v3F2/uQJmglBDB3CNHTQwkyc/xiyK42MEvd+5NxEUD0r/ZsfAtactxAMOCyPN6sgpHqyJ6lCSnh0dxYg2OUWItkJrHGSLkDY7gp37R+Pt+as5lN4JK3w0oSSx5V+3X8kauELDByUIO2dza/wZVUDjcpTd9kHGkSBWKCbuJQv32rVpI4V4yl/H2O0Wz11vAluw=
  - secure: stg2V9kRtDo/3wZfNxaPd3VrKosIS1vLidbrC2VD+tqhz6g+lOY1hd1U7yisUDbPvH3PbP3HYL3WHkADqwIpQVGyCxUoAoEYOj0WfEb31yBaqB1Io3ULrrftGZg1pM63MxV2dVx2Iw1WyjyxCWJgZULYrooDOIfHOMS7siT5kluG1pCwOyWOtTj7DcBLsoh78iAOTpIT8M89L9GbTuTdeGrk2tlcdljL5ykGhnUz1JSghst3+bEqnb/GUIAHDHNyCTDWTIPthOM/+Q1Ny73J2k7KNDgtL7o+8uCx4N6YHC7Wcaa6IvsMW8O5tDsbnEwFnuC6LRM1Khg1sWCwwwBrtAuKW0yfqlA+f+MFoORODEmGpRD4gXYA4lccneh7bQktCRB/EWXxZyrojhIxooOED6TDg0Xt1wPZep5ubmKpozy7rDwdfXa9YmtZbu9Ge42PqRhmi9GUswUVycLX7N3NCai0murdjswN/nRgL8hK5jGFbCjT8ZTZmKYmlg+Xj+vemlLRydC69z3RZnBF3gxsmgENHa3xrTrNuTlZbC2949bX1DjA50hxxgDK2a7QmIn84bcwnEtiVmLZycqV/XfoNtmHrIEejNkxE0pxjtmh60SDqv79SsjRhtCr2bmbOJBxKi2jFNjNG4TER12ynhFbvS7+KpGYWNLdrPBgnJCJmDk=
  - secure: ZwE/DwtBmnFwC/FO2alwyD8gLx+D0l2SEh5Kiz8bLceglf7/E13ftdrfrFNwUEbTDUMxexKmRGW9WJ4/OcEI8wj60ysaSeTGN67Ubiig5vHxtKIOpm9Zy5wmbhXB5b9cw1KhCfAe4oclbSYaJAYcoOKGAbYizAwkIGXYBuNW/vBVDV/e8hsw5zbff72N+asAcffRLLhuWuKAEq3dhi5bkuh0VfIWb9yOKG7FD8osDbhGoxVhdy/yR6MolulU3lYPVuXwBDA4rdGAOMsmTcaWwD2Q2q6QHO1uQoWamu2U2INMWPByVSBIYikpikzMobD8Hab1A9/dA1j3T03GNrTiAf39mxEQgkrSzx6sVuN7GsUyo0TeM491mfN1DWEgu62NnJ9ZsqGgiXXhSI9AQEdYNVY6jBSpOLryEk3MbF3OnWvRmeLFWp+uBIYteo9qteYB/4TO2XHsMqAkXSXJASF9ZNDoH1WSkVxkDLHwdltfUrYC95Tn9afveMZoRC7oHD84y5tYa4nu1zIAeMuhkRQ4sEwaaA6Q/0eNx/R3yJOhIn2ojGTTAuAQUjsGpofRXOUHyB4uRHYqDczQgg15eeppa9lI+eZ28ys078q+tQYpD1JbpLWfSzo0Gh+Yz7cx6NQCDea+stgqCS4Y69sTPJ1F2rpeysTDvHREj3WwdFcS5PI=
before_install: true
install: true
before_script: git lfs pull
script:
- echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
- docker build --build-arg TOKEN=${TOKEN} --build-arg REV=${TRAVIS_COMMIT} --build-arg
  TEST=True -t ${IMAGE} -f docker/Dockerfile docker/
- docker push ${IMAGE}
notifications:
  email:
    recipients:
    - ken.zangelin@fiware.org
    - josemanuel.cantera@fiware.org
    - dmitrii.demin@fiware.org
    on_success: never
    on_failure: always
