name: Deploy Releases

on:
  push:
    branches: [ hardening/CD_global_instance ]

#      -  'release/**'

env:
  IMAGE_NAME: fiware/orion-ld

jobs:
  deploy-release:

    runs-on: ubuntu-18.04
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: jungwinter/split@v1
        id: split
        with:
          msg: ${{ steps.extract_branch.outputs.branch }}
          seperator: /

      - name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.CD_URL_TRIGGER }}
          method: 'GET'
          bearerToken: ${{ secrets.CD_TOKEN }}
