name: Unit Test

on:
  push:
  pull_request:
    branches:
      - develop

env:
  IMAGE_NAME: ghcr.io/wistefan/orion-ld:$GITHUB_RUN_ID

jobs:
  unit:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_token }}

      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/Dockerfile-debian
          build-args: STAGE=deps
          tags: ${{ IMAGE_NAME }}

      - name: Run unit test
        run: |
          docker run -t --rm -v $(pwd):/opt/orion --entrypoint bash -e ORIONLD_CACHED_CONTEXT_DIRECTORY=/opt/orion/ldcontexts $IMAGE_NAME build.sh -s unit -dqt