name: Unit Test

on:
  push:
  pull_request:
    branches:
      - develop

env:
  IMAGE_NAME: ghcr.io/wistefan/orion-ld-test:${{ github.run_id }}

jobs:
  unit:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/Dockerfile-debian
          build-args: STAGE=deps
          tags: localhost:5000/orion-ld-test:latest

      - name: Run unit test
        run: |
          docker run -t --rm -v $(pwd):/opt/orion --entrypoint bash -e ORIONLD_CACHED_CONTEXT_DIRECTORY=/opt/orion/ldcontexts localhost:5000/orion-ld-test:latest build.sh -s unit -dqt